package org.bgi.flexlab.automation.task;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import org.bgi.flexlab.automation.json.WdlOutput;
import org.bgi.flexlab.automation.json.WdlParameter;
import org.bgi.flexlab.automation.json.WdlTask;

import java.io.*;
import java.util.HashMap;

public class TaskWdlBuilder {
    private WdlTask task ;
    private String content ;
    public TaskWdlBuilder(String jsonFile) {
        Gson gson = new Gson() ;
        try {
            Reader jsonReader = new InputStreamReader(new FileInputStream(jsonFile));
            task = gson.fromJson(jsonReader,new TypeToken<WdlTask>(){}.getType()) ;
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    public String getWdlString(){
        String message = "##Generated by BGI.\n##Version : "+task.getVersion()+"\n##Task Description : "+task.getDescription()+"\n" ;
        String parameter = "task " + task.getTaskName() + " {\n" ;
        HashMap<String, WdlParameter> par = task.getParameter() ;
        for(String key : par.keySet()){
            parameter = parameter + " " + par.get(key).getType() ;
            if (par.get(key).isRequired()) {  //required par
                parameter = parameter + " " + key + "\n";
            }else {
                if (par.get(key).getDefaultValue() == null){ // optional && null value
                    parameter = parameter + "? " + key + "\n";
                }else { // optional &&  "" || non-null value
                    parameter = parameter +" " + key + " = " + par.get(key).getDefaultValue()+"\n" ;
                }
            }


        }


        String command = "\tcommand\t{ \n" + "\t\t"+task.getCommand()+"\n"+"\t}\n";
        String runTime = "\truntime\t{ \n" + "\t\tbackends:\"" + task.getBackends()+ "\"\n" + "\t\tsge_queue:queue\"\nmemmory:\"${mem} GB\"\ncpu: cpu\n\t}";
        String output = "\toutput\t{ \n" ;
        HashMap<String, WdlOutput> out = task.getOutput() ;
        for (String key :out.keySet()){ // required  Expre
            output = output + "\t\t"+out.get(key).getType() + " "+ key +" = "+out.get(key).getExpression() + "\n" ;
        }
        output = output + "\t}\n" ;
        content = message +  parameter + command + runTime + output + "}\n";
        return content;
    }

    public String wdlWriter(String outFile){
        try{
            if (content == null || content.equals("")){
                getWdlString();
            }
            BufferedWriter outWriter = new BufferedWriter(new FileWriter(new File(outFile))) ;
            outWriter.write(content);
            outWriter.close();
        }catch (Exception e){
            e.printStackTrace();
        }
        return null;
    }

}
